x86: Fix test-double-vlen include-next
clang issues:

  ../sysdeps/x86_64/fpu/test-double-vlen4.h:20:2: error: #include_next in
  file found relative to primary source file or found by absolute path;
  will search from start of include path
  [-Werror,-Winclude-next-absolute-path]

Instead of suppress the warning, it is simpler to just include the
absolute path instead.